### ISSUE TITLE
Add support for IORING_POLL_ADD_UPDATE

### ISSUE THREAD

**Issue by hassila** [axboe/liburing#310]
Consider adding support for updating to poll operations according to below discussion.

> Or rather that the semantics of IORING_POLL_ADD_MULTI would be that subsequent calls to IORING_POLL_ADD_MULTI with the same user data would replace the previous poll mask in use. Then one could just update away.

I don't like that, because it would mean that any new add would be a lookup as well. If a poll update operation is going to be supported, it should be specifically flagged as such. Eg a ```IORING_POLL_ADD_UPDATE``` flag, for instance, that matches on user_data and re-adds the poll internally based on the new events mask. That would work for both multi and one-shot poll requests.

_Originally posted by @axboe in https://github.com/axboe/liburing/issues/309#issuecomment-801059040_

**Comment by axboe** [comment]
Want to team up on this? I'll update the poll multi branch and add update support, and you run some basic functionality tests on it to ensure that the poll multi works for you, and that the update side does too? That would make my life a lot easier. Bonus points if the functional tests are stand-alone so I can steal them for the regression suite as well :-)

**Comment by hassila** [comment]
Sure, I'd be happy to help out - may need some pointer on where to find info on how to build the kernel pulling in those changes (I'm currently running on Ubuntu 20.04 with a 5.11 kernel put on top for uring). I'm basically testing this out in context of implementing https://github.com/apple/swift-nio/issues/1761 but would be happy to write some stand-alone C basic functionality tests too.

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/linux-block/log/?h=poll-multiple

This has been updated with the patch adding support for poll modifications. They may be done on either a one-shot of multi-shot poll request. See that top commit for a description.

In terms of testing, I'd just poll that branch, build, and boot it. It'll be based on 5.12-rc3 with various things already queued up for 5.13.

**Comment by hassila** [comment]
That's great, I will have a look!

**Comment by axboe** [comment]
FWIW, I did run a simple test case:

1) arm poll request with POLLOUT for the read side of a pipe
2) Check it doesn't complete when data is written to the other side of the pipe
3) Then issue update request with POLLIN set instead
4) Notice that update request completes with res == 0, and original poll request now completes with POLLIN available

That's the extent of testing I did on that patch, JFYI ;-)

**Comment by axboe** [comment]
Just a heads up that I tested multi shot too now, and there's a mask issue so it'll end up turning into a one-shot after that. Fixing that now.

**Comment by axboe** [comment]
Pushed out an updated branch. Only potentially weird thing right now is that the update poll request still needs a file assigned, though it isn't really used. The update ONLY supports changing the event mask on the existing poll request, so we could get away with not requiring an fd set for the update. Just something to keep in mind as you test it, right now with the poll update flag set, the poll request is identical to a "normal" poll add, differing only in requiring you to set ```sqe->addr``` to match the ```user_data``` of the poll request you're updating.

**Comment by hassila** [comment]
Ok, got a box up and running with 5.12.0-rc3-custom based off your branch, will start playing now..

**Comment by hassila** [comment]
Added a first trivial test in https://github.com/axboe/liburing/pull/311 that just tests IORING_POLL_ADD_MULTI.

**Comment by hassila** [comment]
@axboe assume the user_data should be updated too in addition to the poll event mask?

**Comment by axboe** [comment]
> assume the user_data should be updated too in addition to the poll event mask?

Why? Then we'd need to pass that in too. The updated command is still the same, just a new mask.

**Comment by hassila** [comment]
Sorry, I will confess to have been stuffing other data in there (fd + current event mask) as I didn't want to dereference a pointer (in the swift nio implementation the fd is the key to lookup current registrations so this gave me a safe and easy way to keep the needed data circulating). I'll try to think of a better way, but basically that was the rationale (remove need of keeping that pointer ok).

**Comment by axboe** [comment]
Ah I see, I guess that makes sense if you're packing values into that field (which is totally legit, it's for whatever use you would want). In terms of the protocol, it'd be somewhat weird to update user_data too though... We do have room for it so it could be supported, likely we would then do:

```IORING_POLL_UPDATE_EVENTS```    Update events mask
```IORING_POLL_UPDATE_DATA```          Update user_data

and have both be available as a separate flag, and then we'd pass in the ```user_data``` replacement in ```sqe->off``` if UPDATE_DATA is set.

If we do something like that, then it could make sense and would work for your use case.

**Comment by hassila** [comment]
That's be excellent, thanks!

**Comment by axboe** [comment]
Adding, should be ready to test shortly.

**Comment by axboe** [comment]
https://git.kernel.dk/cgit/linux-block/log/?h=poll-multiple

Branch has been updated. There are now two flags, as described above. The commit message has been updated with that info as well. Untested...

**Comment by hassila** [comment]
Updated and testing it now. I see one curios thing (but I believe it is the same on earlier versions) - when I register for poll events with the mask "POLLIN | POLLHUP | POLLERR" I get a first event with cqe->res=0xC3 which is:

```
#define POLLIN		0x0001
#define POLLPRI		0x0002
#define POLLRDNORM	0x0040
#define POLLRDBAND	0x0080
```

Why would I get the later three when I only asked for POLLIN | POLLHUP | POLLERR, it is a bit unexpected ?

**Comment by hassila** [comment]
@axboe I think I have found one issue - when setting up for multiple events for a socket fd with IORING_POLL_ADD_MULTI with the mask POLLIN | POLLHUP | POLLERR, when the other side closes the connection, I just get a POLLIN event (and trying to read, there is 0), but I do not get POLLHUP or POLLERR. I can give you a test program if needed.

**Comment by hassila** [comment]
> Updated and testing it now. I see one curios thing (but I believe it is the same on earlier versions) - when I register for poll events with the mask "POLLIN | POLLHUP | POLLERR" I get a first event with cqe->res=0xC3 which is:
> 
> ```
> #define POLLIN		0x0001
> #define POLLPRI		0x0002
> #define POLLRDNORM	0x0040
> #define POLLRDBAND	0x0080
> ```
> 
> Why would I get the later three when I only asked for POLLIN | POLLHUP | POLLERR, it is a bit unexpected ?

Follow up on that one: I do get it for multiple updates actually (195 below is cqe->res 0xC3, 25 is what was actually registered for - POLLIN | POLLHUP | POLLERR, 5 is just the fd):
```
Server POLLIN on [5] [195] [25]
Server read O
Server: io_uring_wait_cqe
Client writing 
Server POLLIN on [5] [195] [25]
Server read O
Server: io_uring_wait_cqe
Client writing 
Server POLLIN on [5] [195] [25]
Server read O
Server: io_uring_wait_cqe
Client writing 
Server POLLIN on [5] [195] [25]
Server read O
Server: io_uring_wait_cqe
Client closing socket.
Server POLLIN on [5] [195] [25]

```

Expected return value would be just POLLIN.

**Comment by isilence** [comment]
For the 0xC3, I guess It's something like this

```diff
diff --git a/fs/io_uring.c b/fs/io_uring.c
index 4f1c98502a09..559d9653cd92 100644
--- a/fs/io_uring.c
+++ b/fs/io_uring.c
@@ -4869,6 +4869,7 @@ static int __io_async_wake(struct io_kiocb *req, struct io_poll_iocb *poll,
 	/* for instances that support it check for an event match first: */
 	if (mask && !(mask & poll->events))
 		return 0;
+	mask = mask & poll->events;
 
 	trace_io_uring_task_add(req->ctx, req->opcode, req->user_data, mask);
```

**Comment by isilence** [comment]
> @axboe I think I have found one issue - when setting up for multiple events for a socket fd with IORING_POLL_ADD_MULTI with the mask POLLIN | POLLHUP | POLLERR, when the other side closes the connection, I just get a POLLIN event (and trying to read, there is 0), but I do not get POLLHUP or POLLERR. I can give you a test program if needed.

Sounds funky. Yep, please send a test case if you already have it

**Comment by hassila** [comment]
Test added in https://github.com/hassila/liburing/tree/jh-ioring-poll-update-nohup-fail

**Comment by hassila** [comment]
One other small reflection when testing, when I do a modification of the poll mask (ie. switch from POLLIN to POLLOUT), I will receive a CQE with the new POLLOUT signal before I get a 0 return value on the successful modification. I don't think it is a problem, but thought I'd mention it in case you'd expect (or desire) ordering.

**Comment by axboe** [comment]
That ordering is expected, since the poll is removed and re-armed before we complete the update request. Hence if the event is already triggerable when you arm it, it'll generate that event. That'll then come before the update request is finished. Don't think there's anything wrong with that. Would be easy enough to swap them, but honestly don't really see the point?

**Comment by hassila** [comment]
I personally don't think it's a problem, although I think the reverse order (ack first, then event) would feel more natural though for people starting out and debugging, so if its trivial and there is no performance penalty it may be worthwhile for that reason.

**Comment by axboe** [comment]
It makes the code a big uglier, since the natural progression is:

```
Get update request
  Find poll request
  Remove poll request
  Re-issue poll request (this may trigger event)
Complete update request
```

and that nesting naturally ends up dictating the completion order. That said, easy enough to shuffle around.

**Comment by axboe** [comment]
I shuffled them around, ordering should now guarantee that update completes first. In the general case at least, it's of course still possible to race if the poll triggers on the original event mask after you start the update, but before the update finds and disarms the existing poll request. But that's just the (async) nature of the game, nothing can prevent that.

**Comment by hassila** [comment]
That's perfectly fine and expected. Cool!

**Comment by axboe** [comment]
For the hangup case, could this be a case of the socket being referenced by the multishot poll request, hence it never gets a final close? Or does the one-shot successfully get HUP, even if armed?

**Comment by hassila** [comment]
I will investigate a bit more, but one more data point is that if I add POLLRDHUP to the mask, I will get it signalled as expected with multishot when the other end closes.

```
Client writing 
Server POLLIN on [5] [195] [8217]
Server read x
Server: io_uring_wait_cqe
Client closing socket.
Server POLLIN on [5] [195] [8217]
Server read x
Read zero bytes
Server: io_uring_wait_cqe
Server POLLIN on [5] [8193] [8217]
Read zero bytes
Server POLLRDHUP fd [5] [8193] [8217]

```

**Comment by axboe** [comment]
Ah I think it's just a mistake in how we mask events in general, we should always allow unmaskable events like HUP. Let me add an incremental.

**Comment by axboe** [comment]
Nope, we don't get the HUP unless we explicitly ask for it. So I guess you do have to mask it in.

**Comment by hassila** [comment]
But the original mask was POLLIN | POLLHUP | POLLERR, which did not give HUP or ERR.
The second I tried was POLLIN | POLLHUP | POLLERR | POLLRDHUP, which did give RDHUP.
Maybe I'm missing something, but shouldn't the first have worked too?

**Comment by axboe** [comment]
Looks like it's mostly out of our hands, it depends on if the poll is triggered off a socket write or a socket close, basically.

**Comment by axboe** [comment]
Can you try the current branch? I added something on top, let's see if it does the trick for you...

**Comment by hassila** [comment]
Sure, updating to it now (was just writing: Ok, POLLIN and zero available bytes is correct as an EOF, but I would have expected HUP too...).

**Comment by axboe** [comment]
Agree, zero byte read is another hint. But I'd like to get that HUP out if possible, still.

**Comment by hassila** [comment]
I just tried it out now, and when registering with POLLIN | POLLHUP | POLLERR, i got... 0x2001 after the close which is POLLIN | POLL**RD**HUP - so not quite as expected. 

Also, I still get the 0x2c for normal POLLIN events too, but maybe that was not addressed yet.

**Comment by hassila** [comment]
The CQE ordering looks nice though and comes in the natural order now. Noticed on thing more related to masks when doing poll mask modifications related to 0xc3:

Sometimes when doing the poll mask modification (successfully), I would actually get the next event with POLLIN only set (0x01), not 0xc3, immediately followed up by a second CQE with 0xc3 - the second update is a spurious event really, as there was no data ready to be read (and the socket is valid, we continue to read later).

The test basically have an echo server thread and a client that is continuously switching between POLLIN/POLLOUT between events repeatedly.

```
Switching poll mask for fd [7] from [28] to [25] - ok
Client successfully changed poll mask for fd [7] [0] [28] - ok
Client POLLIN on [1] [25] - ok
Client read S - ok
Switching poll mask for fd [7] from [25] to [28] - ok
Client POLLIN on [195] [25] ---- this is unexpected - after this we should have another "Client read S" if there was data
Switching poll mask for fd [7] from [25] to [28] -- this double switch is basically a result of this spurious event - will try to codify that in one part of the test
Client successfully changed poll mask for fd [7] [0] [25] -- and then we got out of sync vs expectations so disregard rest
Client POLLOUT on [4] [28]
Switching poll mask for fd [7] from [28] to [25]
Client POLLOUT on [-2] [25]

```

**Comment by hassila** [comment]
I reduced it down a little bit to a ping-pong test available in https://github.com/axboe/liburing/pull/314/commits/1d7fa2fe15b11cc2509d9caf3480754cccfcd52a

**Comment by hassila** [comment]
I cleaned up the NOHUP test (quite a bit above earlier) and made a PR for it too so the first three tests are available (https://github.com/axboe/liburing/pull/315).

**Comment by hassila** [comment]
Added a fourth test to trigger expected failure (https://github.com/axboe/liburing/pull/316).

**Comment by hassila** [comment]
I merged and packaged the four tests up in https://github.com/axboe/liburing/pull/317 instead to make future integration easier.

**Comment by axboe** [comment]
FWIW, I tried poll-multiple-nohup and just replaced the multishot with a good old poll(2) call - I don't get POLLHUP on that one either...

**Comment by axboe** [comment]
As a more general observation, with io_uring, we keep the file open for poll requests, so you'll be missing out on certain events that are only generated as it goes through final close. So I suspect it's never going to be perfect in that sense, jfyi.

**Comment by hassila** [comment]
Thanks, will need to ponder a bit on those. I guess I don't need perfect, just want to make sure I can get it robust. 

One quick question - I see a poll CQE with ECANCELED (after the socket has been closed) - assuming that signals the poll stream is effectively closed?

**Comment by axboe** [comment]
> One quick question - I see a poll CQE with ECANCELED (after the socket has been closed) - assuming that signals the poll stream is effectively closed?

Since the multishot one is persistent, it keeps being active until you either cancel it, or as it gets canceled as part of ring shutdown (which cancels all pending requests). So that's natural and expected, and happens as part of process or ring exit.

**Comment by hassila** [comment]
Ok, I definitely received it after socket close (while ring & process its still running after), see socket 8 & 9 here which receive ECANCELED (-125) shortly after (it seems natural after a socket close though, its basically a HUP). 

```
...
Shutdown socket 9
...
Shutdown socket 8
[NIOThread(actualName = NIO-ELT-60-#0)] whenReady.block
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_peek_batch_cqe available CQE:s [0x00007fff9405fa70]
[NIOThread(actualName = NIO-ELT-60-#0)] 0 = Optional(0x00007ffff43941f0) | user_data [4294967306] res [0] flags [0] fd[10] eventType[Optional(NIO.CqeEventType.pollModify)]
[NIOThread(actualName = NIO-ELT-60-#0)] 1 = Optional(0x00007ffff4394200) | user_data [4294967306] res [0] flags [0] fd[10] eventType[Optional(NIO.CqeEventType.pollModify)]
[NIOThread(actualName = NIO-ELT-60-#0)] 2 = Optional(0x00007ffff4394210) | user_data [7] res [1] flags [2] fd[7] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 3 = Optional(0x00007ffff4394220) | user_data [7] res [1] flags [2] fd[7] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 4 = Optional(0x00007ffff4394230) | user_data [4294967305] res [0] flags [0] fd[9] eventType[Optional(NIO.CqeEventType.pollModify)]
[NIOThread(actualName = NIO-ELT-60-#0)] 5 = Optional(0x00007ffff4394240) | user_data [9] res [4] flags [2] fd[9] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 6 = Optional(0x00007ffff4394250) | user_data [4294967305] res [0] flags [0] fd[9] eventType[Optional(NIO.CqeEventType.pollModify)]
[NIOThread(actualName = NIO-ELT-60-#0)] 7 = Optional(0x00007ffff4394260) | user_data [9] res [4] flags [2] fd[9] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 8 = Optional(0x00007ffff4394270) | user_data [4294967305] res [0] flags [0] fd[9] eventType[Optional(NIO.CqeEventType.pollModify)]
[NIOThread(actualName = NIO-ELT-60-#0)] 9 = Optional(0x00007ffff4394280) | user_data [9] res [-125] flags [0] fd[9] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] socket is going down [9] [28] [24]
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_peek_batch_cqe returning [2] fdEvents [[9: 28, 7: 1]]
[NIOThread(actualName = NIO-ELT-60-#0)] fds: [(9, 28), (7, 1)] 
[NIOThread(actualName = NIO-ELT-60-#0)] for f in fds 9 28, self.deregistrationsHappened [false]
[NIOThread(actualName = NIO-ELT-60-#0)] We had no registration for fd [9] poll_mask [28] - removing it
[NIOThread(actualName = NIO-ELT-60-#0)] register interested SelectorEventSet(rawValue: 1) uringEventSet [24]
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_prep_poll_add poll_mask[24] fd[8] sqe[Optional(0x00007ffff4294380)] bitpatternAsPointer[Optional(0x0000000000000008)] submitNow[true]
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_flush
[NIOThread(actualName = NIO-ELT-60-#0)] reregister interested SelectorEventSet(rawValue: 3) old SelectorEventSet(rawValue: 1) uringEventSet [8216] reg.uringEventSet [24]
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_poll_update fd[8] oldPollmask[24]  newPollmask[8216] oldBitpatternAsPointer[Optional(0x0000000000000008)] userBitpatternAsPointer[Optional(0x0000000100000008)] userbitPattern[4294967304]
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_flush
[NIOThread(actualName = NIO-ELT-60-#0)] reregister interested SelectorEventSet(rawValue: 7) old SelectorEventSet(rawValue: 3) uringEventSet [8217] reg.uringEventSet [8216]
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_poll_update fd[8] oldPollmask[8216]  newPollmask[8217] oldBitpatternAsPointer[Optional(0x0000000000000008)] userBitpatternAsPointer[Optional(0x0000000100000008)] userbitPattern[4294967304]
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_flush
[NIOThread(actualName = NIO-ELT-60-#0)] whenReady.block
[NIOThread(actualName = NIO-ELT-60-#0)] io_uring_peek_batch_cqe available CQE:s [0x00007fff9405fa70]
[NIOThread(actualName = NIO-ELT-60-#0)] 0 = Optional(0x00007ffff4394290) | user_data [9] res [0] flags [0] fd[9] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 1 = Optional(0x00007ffff43942a0) | user_data [10] res [8193] flags [2] fd[10] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 2 = Optional(0x00007ffff43942b0) | user_data [7] res [1] flags [2] fd[7] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 3 = Optional(0x00007ffff43942c0) | user_data [7] res [1] flags [2] fd[7] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 4 = Optional(0x00007ffff43942d0) | user_data [8] res [-125] flags [0] fd[8] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 5 = Optional(0x00007ffff43942e0) | user_data [8] res [0] flags [0] fd[8] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 6 = Optional(0x00007ffff43942f0) | user_data [7] res [1] flags [2] fd[7] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 7 = Optional(0x00007ffff4394300) | user_data [7] res [1] flags [2] fd[7] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 8 = Optional(0x00007ffff4394310) | user_data [7] res [1] flags [2] fd[7] eventType[Optional(NIO.CqeEventType.poll)]
[NIOThread(actualName = NIO-ELT-60-#0)] 9 = Optional(0x00007ffff4394320) | user_data [7] res [1] flags [2] fd[7] eventType[Optional(NIO.CqeEventType.poll)]
...

```

**Comment by axboe** [comment]
Is the cqring overflowing?

**Comment by hassila** [comment]
I'll check, it is possible - I've set it up with `io_uring_queue_init(4096, ..` which felt like a large size for the tests I'm doing.

**Comment by axboe** [comment]
Would be quite a feat to overflow that, so probably not overflow I would think. Are you using multiple tasks/threads?

**Comment by hassila** [comment]
Yes, there are a handful of threads, basically I am running through the SwiftNIO unit test suite right now and the same process will keep running creating/tearing down urings repeatedly (as part of running the actual test which can be e.g. running an HTTP server/client etc). Some tests may run with NCPUS (currently 8, running on AWS) but each ring is only accessed through a single dedicated thread. Using a multishot poll eventfd for waking it up when needed.

**Comment by axboe** [comment]
Are the threads persistent, or do they exist? What I'm getting at is if you have a thread issue a poll request, then later exit with that still pending?

**Comment by hassila** [comment]
They do exit when they are done typically, but in this case it was all done by the same thread 'NIO-ELT-60-#0' is a readable thread id (so that was the first spawned NIO thread (#0) of EventLoopTest #60). So for that example there were a handful of threads still "live" from pervious tests but none of them can touch the ring for that thread;

```
(lldb) thread list
Process 17401 stopped
  thread #1: tid = 17401, 0x00007ffff7a37376 libpthread.so.0`__pthread_cond_wait at futex-internal.h:183:13, name = 'swift-nioPackag'
  thread #3: tid = 17434, 0x00007ffff7a3a618 libpthread.so.0`do_futex_wait at futex-internal.h:320:13, name = 'NIO-ELT-0-#0'
  thread #4: tid = 17435, 0x00007ffff6f2a5ce libc.so.6`epoll_wait + 94, name = 'NIO-ELT-0-#0'
  thread #5: tid = 17436, 0x00007ffff7a3a618 libpthread.so.0`do_futex_wait at futex-internal.h:320:13, name = 'NIO-ELT-0-#0'
  thread #6: tid = 17473, 0x00007ffff7a3a618 libpthread.so.0`do_futex_wait at futex-internal.h:320:13, name = 'swift-nioPackag'
  thread #7: tid = 17494, 0x00007ffff7a3a618 libpthread.so.0`do_futex_wait at futex-internal.h:320:13, name = 'NIO-ELT-0-#0'
* thread #10: tid = 17610, 0x00007ffff7e4ef80 libswiftCore.so`_swift_runtime_on_report, name = 'NIO-ELT-60-#0', stop reason = Fatal error: got .readEOF and read returned not reading any bytes, nor EOF.
(lldb) 
```

**Comment by hassila** [comment]
Ok, some good news - I've moved SwiftNIO (https://github.com/apple/swift-nio/issues/1761) on top of the new multishot poll/modify and is passing all tests except a handful (of 1300+) - there is one issue there with EOF, but can't pin root cause to the work in this case as of yet, needs investigation. 

Remaining question marks here I think are:
1. the 0xc3 poll masks
2. the failing ping-pong test 
3. the one with missing HUP, (but you tried with a normal poll and didn't get it either... I will check with epoll too soon and see how it behaves...)

**Comment by hassila** [comment]
I've encountered the following (a number of kernel IO threads running at 100%) a few times which have required a reboot - not sure if it is related to streaming polls, but mentioning it:

![image](https://user-images.githubusercontent.com/8501048/112358636-d0da8480-8cd0-11eb-88b7-c290363feec9.png)

**Comment by axboe** [comment]
Right, in my testing poll(2) and io_uring had the same behavior, the io_uring mask is just added to internally. For the important part, I got POLLIN for both where we would have expected POLLHUP.

For the iou-mgr-xxxx spinning, let me know if you find a way to reproduce that, I'd love to take a look. What git sha were you running?

**Comment by hassila** [comment]
I was running commit ada3a81f8966877523165b40ea6d3c7942c982e8.

I think I may possibly know how to reproduce it, fundamentally I had a too small ring size which made one of the test get stuck in the following code (Swift), so I had a process looping in:

   ```
 public func io_uring_flush() {         // When using SQPOLL this is just a NOP
        var submissiontimes = 0
        var retval : Int32
        
        // FIXME:  it may return -EAGAIN or -ENOMEM when there is not enough memory to do internal allocations.
        while (CNIOLinux_io_uring_sq_ready(&ring) > 0)
        {
            retval = CNIOLinux_io_uring_submit(&ring)
            submissiontimes += 1

            // FIXME: We will fail here if the ring is too small, one of the allocation
            // tests required 1K ring size minimum to run as it was doing registration
            // mask notification repeatedly in a loop...
            if submissiontimes > 1 {
                if (retval == -EAGAIN)
                {
                     _debugPrint("io_uring_flush io_uring_submit -EAGAIN \(submissiontimes)")

                }
                if (retval == -ENOMEM)
                {
                     _debugPrint("io_uring_flush io_uring_submit -ENOMEM \(submissiontimes)")
                }
                 _debugPrint("io_uring_flush io_uring_submit needed \(submissiontimes)")
            }
        }
    }
```

I think it may be when I eventually killed that it started running - just providing as possible cause - don't have time to test right now. 

If that isn't the reproduced, I can likely do it by running the SwiftNIO integration tests a number of times... I had the spinning three times during today.

**Comment by hassila** [comment]
So to clarify, that amok process received a kill -9.

**Comment by axboe** [comment]
OK, that should be fixed in the current tree. Do let me know if you run into it again with the newer branch (33021a19e324fb747c2038416753e63fd7cd9266 as of this writing), it had to do with signal deliveries not being always properly ignored for IO threads.

**Comment by hassila** [comment]
Ok, I’ve updated- will let you know it happens again.

**Comment by hassila** [comment]
Not had that problem again, but I see one possibly strange other behaviour - I'd get SIGPIPE for some write():s even if we have set up signal(SIGPIPE, SIG_IGN) earlier. Could it be related to signal deliveries you mentioned? Im at cd9266.

**Comment by hassila** [comment]
Ok, I have done quite a lot more testing now and still have issues with ECANCELED being received, it comes as a pair with EALREADY for the poll modify followed by ECANCELED for the multishot poll - can it be that EALREADY for the poll modify remove the ongoing poll and generates an ECANCELED unexpectedly?

The final poll modify below fails with ENOENT as the previous multishot poll had been ECANCELED (but the question is why...?)

I can see that the socket is still alive after, as I can first read from it and then subsequently get a 'would block' on the final read on the fd - and the process is not going down (the uring is still valid and this is done from the same thread).

```
Q [NIOThread(actualName = NIO-ELT-0-#2)] io_uring_peek_batch_cqe CQE:s [0x00007fd218000d20] - ring flags are [0]
Q [NIOThread(actualName = NIO-ELT-0-#2)] 0 = fd[24] eventType[Optional(NIO.CqeEventType.pollModify)] res [0] flags [0]  bitpattern[Optional(0x0000000200000018)]
Q [NIOThread(actualName = NIO-ELT-0-#2)] io_uring_wait_cqe CQE:s [0x00007fd218000d20] - ring flags are [0]
Q [NIOThread(actualName = NIO-ELT-0-#2)] 0 = fd[24] eventType[Optional(NIO.CqeEventType.poll)] res [195] flags [2]  bitpattern[Optional(0x0000000100000018)]
B [NIOThread(actualName = NIO-ELT-0-#2)] Read [1325] from socket
B [NIOThread(actualName = NIO-ELT-0-#2)] Read has buffer.writableBytes[723]] result[some]
B [NIOThread(actualName = NIO-ELT-0-#2)] readResult = try self.readFromSocket() [some]
Q [NIOThread(actualName = NIO-ELT-0-#2)] io_uring_peek_batch_cqe CQE:s [0x00007fd218000d20] - ring flags are [0]
Q [NIOThread(actualName = NIO-ELT-0-#2)] 0 = fd[24] eventType[Optional(NIO.CqeEventType.pollModify)] res [0] flags [0]  bitpattern[Optional(0x0000000200000018)]
Q [NIOThread(actualName = NIO-ELT-0-#2)] io_uring_wait_cqe CQE:s [0x00007fd218000d20] - ring flags are [0]
Q [NIOThread(actualName = NIO-ELT-0-#2)] 0 = fd[24] eventType[Optional(NIO.CqeEventType.poll)] res [195] flags [2]  bitpattern[Optional(0x0000000100000018)]
B [NIOThread(actualName = NIO-ELT-0-#2)] Read [1325] from socket
B [NIOThread(actualName = NIO-ELT-0-#2)] Read has buffer.writableBytes[723]] result[some]
B [NIOThread(actualName = NIO-ELT-0-#2)] readResult = try self.readFromSocket() [some]
Q [NIOThread(actualName = NIO-ELT-0-#2)] io_uring_peek_batch_cqe CQE:s [0x00007fd218000d20] - ring flags are [0]
Q [NIOThread(actualName = NIO-ELT-0-#2)] 0 = fd[24] eventType[Optional(NIO.CqeEventType.pollModify)] res [-114] flags [0]  bitpattern[Optional(0x0000000200000018)]
Q [NIOThread(actualName = NIO-ELT-0-#2)] 1 = fd[24] eventType[Optional(NIO.CqeEventType.poll)] res [-125] flags [0]  bitpattern[Optional(0x0000000100000018)]
B [NIOThread(actualName = NIO-ELT-0-#2)] Read [1325] from socket
B [NIOThread(actualName = NIO-ELT-0-#2)] Read has buffer.writableBytes[723]] result[some]
B [NIOThread(actualName = NIO-ELT-0-#2)] readResult = try self.readFromSocket() [some]
Q [NIOThread(actualName = NIO-ELT-0-#2)] io_uring_peek_batch_cqe CQE:s [0x00007fd218000d20] - ring flags are [0]
Q [NIOThread(actualName = NIO-ELT-0-#2)] 0 = fd[24] eventType[Optional(NIO.CqeEventType.pollModify)] res [-2] flags [0]  bitpattern[Optional(0x0000000200000018)]
B [NIOThread(actualName = NIO-ELT-0-#2)] reset -> readEOF0
B [NIOThread(actualName = NIO-ELT-0-#2)] readEOF0 -> switch self.readable0()
B [NIOThread(actualName = NIO-ELT-0-#2)] Read [1325] from socket
B [NIOThread(actualName = NIO-ELT-0-#2)] Read has buffer.writableBytes[723]] result[some]
B [NIOThread(actualName = NIO-ELT-0-#2)] readResult = try self.readFromSocket() [some]
B [NIOThread(actualName = NIO-ELT-0-#2)] readEOF0 -> switch self.readable0()
B [NIOThread(actualName = NIO-ELT-0-#2)] Read wouldBlock!
B [NIOThread(actualName = NIO-ELT-0-#2)] readResult = try self.readFromSocket() [none]
```

**Comment by axboe** [comment]
OK I see what the problem is, there's basically a race with updating where we have it marked canceled for a brief period. If that coincides with the poll event actually triggering, then you can get the ECANCELED. I'll take a stab at fixing this up, and then I'll ask you to re-test for this particular event.

**Comment by hassila** [comment]
Super, looking forward to testing it!

**Comment by axboe** [comment]
Pushed it out:

https://git.kernel.dk/cgit/linux-block/commit/?h=for-5.13/io_uring&id=e1358bf0a7b0688334865d205db5710d87978a7f

(I'll need your email address to put in the report, just used your name for now).

**Comment by hassila** [comment]
Ok, testing now - I am at joj(a)mac.com

**Comment by hassila** [comment]
So it's not on the poll-multiple branch, can I use for-5.13/io_uring ??

**Comment by axboe** [comment]
Right, just use for-5.13/io_uring - I've queued up the feature for 5.13, so the old poll-multiple branch is no longer getting updated.

**Comment by hassila** [comment]
Ok, ran the test - I no longer did get ECANCELED, but instead the next poll modify gave me ENOENT:

```
EALREADY -> Q [NIOThread(actualName = NIO-ELT-0-#6)] 0 = fd[20] eventType[Optional(NIO.CqeEventType.pollModify)] res [-114] flags [0]  bitpattern[Optional(0x0000000200000014)]
OK POLL (except 195 instead of 1, but different topic) -> Q [NIOThread(actualName = NIO-ELT-0-#6)] 1 = fd[20] eventType[Optional(NIO.CqeEventType.poll)] res [195] flags [2]  bitpattern[Optional(0x0000000100000014)]
L [NIOThread(actualName = NIO-ELT-0-#6)] io_uring_peek_batch_cqe returning [1] events
S [NIOThread(actualName = NIO-ELT-0-#6)] We found a registration for event.fd [20]
S [NIOThread(actualName = NIO-ELT-0-#6)] selectorEvent [SelectorEventSet(rawValue: 4)] registration.interested [SelectorEventSet(rawValue: 7)]
S [NIOThread(actualName = NIO-ELT-0-#6)] intersection [SelectorEventSet(rawValue: 4)]
S [NIOThread(actualName = NIO-ELT-0-#6)] running body [NIOThread(actualName = NIO-ELT-0-#6)] SelectorEventSet(rawValue: 4) SelectorEventSet(rawValue: 4)
POLL MODIFY -> L [NIOThread(actualName = NIO-ELT-0-#6)] io_uring_poll_update fd[20] oldPollmask[8217] newPollmask[8217]  userBitpatternAsPointer[Optional(0x0000000200000014)]
B [NIOThread(actualName = NIO-ELT-0-#6)] Read [1325] from socket
B [NIOThread(actualName = NIO-ELT-0-#6)] Read has buffer.writableBytes[723]] result[some]
B [NIOThread(actualName = NIO-ELT-0-#6)] readResult = try self.readFromSocket() [some]
L [NIOThread(actualName = NIO-ELT-0-#6)] io_uring_flush
L [NIOThread(actualName = NIO-ELT-0-#6)] io_uring_flush io_uring_submit needed [1] submission(s), submitted [1] SQE:s out of [1] possible
L [NIOThread(actualName = NIO-ELT-0-#6)] io_uring_flush done
S [NIOThread(actualName = NIO-ELT-0-#6)] whenReady.block
L [NIOThread(actualName = NIO-ELT-0-#6)] io_uring_peek_batch_cqe
Q [NIOThread(actualName = NIO-ELT-0-#6)] io_uring_peek_batch_cqe CQE:s [0x00007fffd0000d20] - ring flags are [0]
ENOENT on modify ->Q [NIOThread(actualName = NIO-ELT-0-#6)] 0 = fd[20] eventType[Optional(NIO.CqeEventType.pollModify)] res [-2] flags [0]  bitpattern[Optional(0x0000000200000014)]
```

**Comment by axboe** [comment]
Try with the updated for-5.13/io_uring branch

**Comment by hassila** [comment]
Yep. Running with two performance testers in parallel I got this:

```
shell 1:
> swift run -c release NIOPerformanceTester

[16/16] Linking NIOPerformanceTester
measuring: write_http_headers: 0.004494366, 0.004499905, 0.004461707, 0.004533724, 0.004510291, 0.00451973, 0.00448578, 0.004493824, 0.004494457, 0.004510075, 
measuring: bytebuffer_write_12MB_short_string_literals: 0.584404005, 0.581579155, 0.580218143, 0.582028285, 0.578503778, 0.577581803, 0.577967812, 0.580803146, 0.57924377, 0.580197958, 
measuring: bytebuffer_write_12MB_short_calculated_strings: 0.579273883, 0.579462935, 0.579823101, 0.578487303, 0.576997499, 0.578403646, 0.578652032, 0.577664075, 0.579994964, 0.578558049, 
measuring: bytebuffer_write_12MB_medium_string_literals: 0.19182859, 0.191054069, 0.189970607, 0.188840789, 0.190562756, 0.189545448, 0.191278866, 0.19234315, 0.190367161, 0.189116426, 
measuring: bytebuffer_write_12MB_medium_calculated_strings: 0.229731588, 0.228453242, 0.228909992, 0.231350844, 0.231038935, 0.231807807, 0.231011357, 0.23132304, 0.231299574, 0.231847658, 
measuring: bytebuffer_write_12MB_large_calculated_strings: 0.21018037, 0.20963283, 0.209584216, 0.209666185, 0.209701968, 0.209677557, 0.209538079, 0.209889876, 0.209670165, 0.209762553, 
measuring: bytebuffer_lots_of_rw: 0.50887119, 0.508708687, 0.508656112, 0.508501158, 0.508800806, 0.508685292, 0.508814074, 0.509110433, 0.508720156, 0.509326709, 
measuring: bytebuffer_write_http_response_ascii_only_as_string: 0.04412232, 0.043763745, 0.044147338, 0.043975263, 0.044204645, 0.044328474, 0.044105043, 0.043973574, 0.04392608, 0.043883604, 
measuring: bytebuffer_write_http_response_ascii_only_as_staticstring: 0.035429151, 0.035176613, 0.035300536, 0.035203583, 0.035195208, 0.035064425, 0.035160881, 0.03504292, 0.035181467, 0.035061062, 
measuring: bytebuffer_write_http_response_some_nonascii_as_string: 0.044138992, 0.044004945, 0.044136542, 0.044124027, 0.043868072, 0.044157429, 0.044111878, 0.043998308, 0.044256736, 0.044028298, 
measuring: bytebuffer_write_http_response_some_nonascii_as_staticstring: 0.035004073, 0.035106019, 0.035413979, 0.0350201, 0.035128684, 0.034937436, 0.034897572, 0.035030493, 0.03499149, 0.035070988, 
measuring: no-net_http1_10k_reqs_1_conn: 0.116432061, 0.116081598, 0.116171385, 0.115291886, 0.115834835, 0.115507511, 0.115824976, 0.116325356, 0.115673658, 0.115721351, 

Message from syslogd@ip-172-31-25-161 at Apr  1 06:16:13 ...
 kernel:[  204.789847] watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [NIO-ELT-0-#2:1621]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:16:13 ...
 kernel:[  204.793846] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [swapper/1:0]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:16:13 ...
 kernel:[  204.833844] watchdog: BUG: soft lockup - CPU#5 stuck for 22s! [NIO-ELT-0-#3:1622]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:16:13 ...
 kernel:[  204.841847] watchdog: BUG: soft lockup - CPU#6 stuck for 22s! [NIO-ELT-0-#3:1666]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:16:13 ...
 kernel:[  204.849845] watchdog: BUG: soft lockup - CPU#7 stuck for 22s! [swapper/7:0]
```

shell 2 (idle):
```
Type help for instructions on how to use fish
> 
Message from syslogd@ip-172-31-25-161 at Apr  1 06:16:13 ...
 kernel:[  204.789847] watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [NIO-ELT-0-#2:1621]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:16:13 ...
 kernel:[  204.793846] watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [swapper/1:0]
```

And the machine was hung...

It was an AWS c5.2xlarge instance.

**Comment by hassila** [comment]
Yep, 100% reproducible - now I only run a single ssh session into the box and run a single performance tester:

```
ubuntu@ip-172-31-25-161 ~/s/swift-nio (jh-liburing-dev-new)> swift run -c release NIOPerformanceTester
measuring: write_http_headers: 0.004550229, 0.004496422, 0.004517031, 0.004519137, 0.004502171, 0.004492022, 0.004493017, 0.00450815, 0.004486889, 0.004494683, 
measuring: bytebuffer_write_12MB_short_string_literals: 0.589014523, 0.586297921, 0.624012149, 0.598655014, 0.574106295, 0.574309857, 0.572869805, 0.573346968, 0.573268239, 0.572063554, 
measuring: bytebuffer_write_12MB_short_calculated_strings: 0.57387424, 0.574452691, 0.574981476, 0.57492529, 0.574481949, 0.573463482, 0.573076721, 0.574413446, 0.574437253, 0.576253311, 
measuring: bytebuffer_write_12MB_medium_string_literals: 0.190516392, 0.191142215, 0.191614382, 0.190883064, 0.190633412, 0.190155709, 0.190602828, 0.191103543, 0.19091249, 0.190196824, 
measuring: bytebuffer_write_12MB_medium_calculated_strings: 0.230873642, 0.230693585, 0.23067311, 0.23079483, 0.230641072, 0.230710061, 0.230558257, 0.232708788, 0.230522265, 0.230725614, 
measuring: bytebuffer_write_12MB_large_calculated_strings: 0.210928233, 0.211123815, 0.212750589, 0.212636695, 0.211943466, 0.213467541, 0.213527841, 0.213315849, 0.211407996, 0.211400783, 
measuring: bytebuffer_lots_of_rw: 0.510836839, 0.510729004, 0.51086573, 0.51089498, 0.510799802, 0.510916719, 0.510759251, 0.510834955, 0.510664286, 0.510808278, 
measuring: bytebuffer_write_http_response_ascii_only_as_string: 0.043977856, 0.043877188, 0.043885528, 0.043992056, 0.043827801, 0.04392914, 0.043986669, 0.043852266, 0.04388532, 0.043973678, 
measuring: bytebuffer_write_http_response_ascii_only_as_staticstring: 0.035375534, 0.03537783, 0.035383478, 0.035371566, 0.035348059, 0.035344955, 0.035374083, 0.03513121, 0.03524334, 0.035076012, 
measuring: bytebuffer_write_http_response_some_nonascii_as_string: 0.044209525, 0.04414642, 0.044187465, 0.044379608, 0.044109767, 0.044211627, 0.044057732, 0.044165613, 0.044451202, 0.044135708, 
measuring: bytebuffer_write_http_response_some_nonascii_as_staticstring: 0.035255782, 0.035253007, 0.035180606, 0.035179209, 0.035163497, 0.035200652, 0.035254322, 0.035063253, 0.035265236, 0.034933209, 
measuring: no-net_http1_10k_reqs_1_conn: 0.115001662, 0.115097848, 0.115307013, 0.115714913, 0.115399475, 0.115655498, 0.114796984, 0.115574058, 0.11476568, 0.115629214, 

Message from syslogd@ip-172-31-25-161 at Apr  1 06:30:57 ...
 kernel:[   80.805955] watchdog: BUG: soft lockup - CPU#3 stuck for 23s! [NIO-ELT-0-#5:1006]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:30:57 ...
 kernel:[   80.829955] watchdog: BUG: soft lockup - CPU#5 stuck for 23s! [NIO-ELT-0-#6:1007]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:30:57 ...
 kernel:[   80.845955] watchdog: BUG: soft lockup - CPU#7 stuck for 23s! [swapper/7:0]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:31:25 ...
 kernel:[  108.805916] watchdog: BUG: soft lockup - CPU#3 stuck for 23s! [NIO-ELT-0-#5:1006]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:31:25 ...
 kernel:[  108.829917] watchdog: BUG: soft lockup - CPU#5 stuck for 22s! [NIO-ELT-0-#6:1007]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:31:25 ...
 kernel:[  108.845917] watchdog: BUG: soft lockup - CPU#7 stuck for 22s! [swapper/7:0]
^C^C^C^Z
Message from syslogd@ip-172-31-25-161 at Apr  1 06:32:01 ...
 kernel:[  144.805898] watchdog: BUG: soft lockup - CPU#3 stuck for 22s! [NIO-ELT-0-#5:1006]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:32:01 ...
 kernel:[  144.829899] watchdog: BUG: soft lockup - CPU#5 stuck for 22s! [NIO-ELT-0-#6:1007]
```

**Comment by hassila** [comment]
Tried a third time, same - will revert to previous version..

```
ubuntu@ip-172-31-25-161 ~/s/swift-nio (jh-liburing-dev-new)> swift run -c release NIOPerformanceTester
[2/2] Linking NIOPerformanceTester
measuring: write_http_headers: 0.004697473, 0.004717718, 0.004734297, 0.004700758, 0.004670844, 0.004699837, 0.004695593, 0.004709851, 0.004694421, 0.004698188, 
measuring: bytebuffer_write_12MB_short_string_literals: 0.585972141, 0.579374845, 0.580829438, 0.580426991, 0.579594051, 0.580175372, 0.579626287, 0.581472142, 0.580332649, 0.580618588, 
measuring: bytebuffer_write_12MB_short_calculated_strings: 0.582711818, 0.584913252, 0.584264697, 0.582105712, 0.584224558, 0.584422743, 0.584751049, 0.584616451, 0.581931651, 0.583415069, 
measuring: bytebuffer_write_12MB_medium_string_literals: 0.193670901, 0.192978809, 0.193633887, 0.191589681, 0.191169864, 0.190738761, 0.19155718, 0.192663431, 0.190557156, 0.190756443, 
measuring: bytebuffer_write_12MB_medium_calculated_strings: 0.228108126, 0.247255368, 0.228032179, 0.247206164, 0.228589527, 0.248070418, 0.228732661, 0.247735989, 0.228782615, 0.247968825, 
measuring: bytebuffer_write_12MB_large_calculated_strings: 0.208585724, 0.207706391, 0.209242059, 0.208836441, 0.208604478, 0.208934223, 0.208854167, 0.207908083, 0.207992159, 0.208420994, 
measuring: bytebuffer_lots_of_rw: 0.510001173, 0.516663875, 0.510346558, 0.516735831, 0.510025856, 0.516671374, 0.51005605, 0.516671774, 0.509930332, 0.516657521, 
measuring: bytebuffer_write_http_response_ascii_only_as_string: 0.043601802, 0.043558134, 0.043534406, 0.04366452, 0.043639072, 0.043467858, 0.04342406, 0.043504937, 0.04358142, 0.043566282, 
measuring: bytebuffer_write_http_response_ascii_only_as_staticstring: 0.035503634, 0.035400278, 0.035374071, 0.03550759, 0.03538871, 0.035323753, 0.035330666, 0.035377247, 0.03544315, 0.035377479, 
measuring: bytebuffer_write_http_response_some_nonascii_as_string: 0.044337408, 0.043902297, 0.043879411, 0.043877593, 0.044260065, 0.043832352, 0.044065455, 0.044102653, 0.044266135, 0.044247051, 
measuring: bytebuffer_write_http_response_some_nonascii_as_staticstring: 0.035630678, 0.035723467, 0.03561343, 0.035918586, 0.035611439, 0.03563605, 0.035666571, 0.035686051, 0.035599987, 0.035667926, 
measuring: no-net_http1_10k_reqs_1_conn: 0.116588183, 0.116790887, 0.115942759, 0.115676267, 0.116605832, 0.116546163, 0.116180206, 0.116324858, 0.116534011, 0.117254669, 

Message from syslogd@ip-172-31-25-161 at Apr  1 06:39:14 ...
 kernel:[  120.819106] watchdog: BUG: soft lockup - CPU#3 stuck for 22s! [swapper/3:0]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:39:14 ...
 kernel:[  120.843108] watchdog: BUG: soft lockup - CPU#5 stuck for 22s! [NIO-ELT-0-#2:1210]

Message from syslogd@ip-172-31-25-161 at Apr  1 06:39:14 ...
 kernel:[  120.859105] watchdog: BUG: soft lockup - CPU#7 stuck for 22s! [NIO-ELT-0-#1:1209]
```

Just for reference correct sha:
```
ubuntu@ip-172-31-25-161 ~/k/linux-block (for-5.13/io_uring)> git rev-parse --verify HEAD
e3ca6d4f3803f83cb19239cc865cc4d42dc27d64
ubuntu@ip-172-31-25-161 ~/k/linux-block (for-5.13/io_uring)> uname -a
Linux ip-172-31-25-161 5.12.0-rc5-5.13-uring-210401 #1 SMP Thu Apr 1 06:01:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-25-161 ~/k/linux-block (for-5.13/io_uring)> git log
commit e3ca6d4f3803f83cb19239cc865cc4d42dc27d64 (HEAD -> for-5.13/io_uring, origin/for-5.13/io_uring)
...
```

**Comment by hassila** [comment]
Previous version (the one with ENOENT) runs fine without hangs, just verified.

**Comment by hassila** [comment]
Although when trying SQPOLL kernel side polling I've gotten the following weird state after trying to kill the performance tester process after it seemed to get stuck:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/8501048/113260180-40063900-92ce-11eb-93c4-0d219a473a95.png">

and the NIOPerformanceTester process ended up as defunct.

`0 Z ubuntu      1499       1 58  80   0 -     0 -      07:07 ?        00:18:00 [NIOPerformanceT] <defunct>
`

**Comment by hassila** [comment]
I think this works fine now, I will try to allocate time to fix up the tests soon.

**Comment by hassila** [comment]
The related tests are fixed up in the PR, not sure what more remains here?

**Comment by axboe** [comment]
Let's close it up! Thanks for being super helpful in testing this feature, that's always key to a good final outcome.
